"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔍 CONTROL TOTAL DEL .env: Buscamos el archivo de manera estricta
_env_path = BASE_DIR / ".env"

if _env_path.is_file():
    # Forzamos a Python a sobreescribir cualquier dato viejo en memoria
    load_dotenv(dotenv_path=_env_path, override=True)
else:
    raise ImproperlyConfigured(
        f"\n❌ ERROR CRÍTICO: No se encontró el archivo .env en la ruta esperada:\n"
        f"👉 {_env_path}\n"
        f"Por favor, asegúrate de que el archivo se llame exactamente '.env' (sin .txt ni .example) "
        f"y que esté guardado dentro de la carpeta 'backend'."
    )

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-h2libc0+t3y6n$a@ljy1_1$5vry1#e(4jkprg_2e5hm2l1ysbf'
DEBUG = True
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.postgres',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# 🗄️ Database Configuration & Validation
def _require_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise ImproperlyConfigured(
            f"La variable de entorno '{name}' está vacía o no existe en tu archivo .env."
        )
    return value

_db_required = ("DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST", "DB_PORT")
_missing = [key for key in _db_required if not os.getenv(key, "").strip()]

if _missing:
    raise ImproperlyConfigured(
        f"\n⚠️ FALTAN VARIABLES EN TU ARCHIVO .env:\n"
        f"Faltan las siguientes claves: {', '.join(_missing)}\n"
        f"Ruta del archivo leído: {_env_path}\n"
        f"Valores actuales detectados por Django:\n"
        f" - DB_NAME: {os.getenv('DB_NAME')}\n"
        f" - DB_USER: {os.getenv('DB_USER')}\n"
        f" - DB_HOST: {os.getenv('DB_HOST')}\n"
    )

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _require_env("DB_NAME"),
        "USER": _require_env("DB_USER"),
        "PASSWORD": _require_env("DB_PASSWORD"),
        "HOST": _require_env("DB_HOST"),
        "PORT": _require_env("DB_PORT"),
        "OPTIONS": {
            "sslmode": os.getenv("DB_SSLMODE", "require").strip() or "require",
        },
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Permisos de comunicación (CORS)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  
    "http://localhost:8080",  # Tu React corriendo en Vite local
]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "EXCEPTION_HANDLER": "api.exceptions.contam_exception_handler",
}