/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVentasRouteImport } from './routes/_app.ventas'
import { Route as AppSireRouteImport } from './routes/_app.sire'
import { Route as AppEntidadesRouteImport } from './routes/_app.entidades'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppComprasRouteImport } from './routes/_app.compras'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVentasRoute = AppVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AppRoute,
} as any)
const AppSireRoute = AppSireRouteImport.update({
  id: '/sire',
  path: '/sire',
  getParentRoute: () => AppRoute,
} as any)
const AppEntidadesRoute = AppEntidadesRouteImport.update({
  id: '/entidades',
  path: '/entidades',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/compras': typeof AppComprasRoute
  '/dashboard': typeof AppDashboardRoute
  '/entidades': typeof AppEntidadesRoute
  '/sire': typeof AppSireRoute
  '/ventas': typeof AppVentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/compras': typeof AppComprasRoute
  '/dashboard': typeof AppDashboardRoute
  '/entidades': typeof AppEntidadesRoute
  '/sire': typeof AppSireRoute
  '/ventas': typeof AppVentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/compras': typeof AppComprasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/entidades': typeof AppEntidadesRoute
  '/_app/sire': typeof AppSireRoute
  '/_app/ventas': typeof AppVentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/compras'
    | '/dashboard'
    | '/entidades'
    | '/sire'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/compras'
    | '/dashboard'
    | '/entidades'
    | '/sire'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/compras'
    | '/_app/dashboard'
    | '/_app/entidades'
    | '/_app/sire'
    | '/_app/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ventas': {
      id: '/_app/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AppVentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sire': {
      id: '/_app/sire'
      path: '/sire'
      fullPath: '/sire'
      preLoaderRoute: typeof AppSireRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entidades': {
      id: '/_app/entidades'
      path: '/entidades'
      fullPath: '/entidades'
      preLoaderRoute: typeof AppEntidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compras': {
      id: '/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppComprasRoute: typeof AppComprasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEntidadesRoute: typeof AppEntidadesRoute
  AppSireRoute: typeof AppSireRoute
  AppVentasRoute: typeof AppVentasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComprasRoute: AppComprasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEntidadesRoute: AppEntidadesRoute,
  AppSireRoute: AppSireRoute,
  AppVentasRoute: AppVentasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
