/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSireRegistrosRouteImport } from './routes/_app.sire-registros'
import { Route as AppPcgeRouteImport } from './routes/_app.pcge'
import { Route as AppLibroDiarioRouteImport } from './routes/_app.libro-diario'
import { Route as AppLibroCajaRouteImport } from './routes/_app.libro-caja'
import { Route as AppFichaRucRouteImport } from './routes/_app.ficha-ruc'
import { Route as AppDashboardEstadisticasRouteImport } from './routes/_app.dashboard-estadisticas'
import { Route as AppContribuyentesRouteImport } from './routes/_app.contribuyentes'
import { Route as AppCancelacionesRouteImport } from './routes/_app.cancelaciones'
import { Route as ApiStatsKpisRouteImport } from './routes/api/stats/kpis'
import { Route as ApiStatsChartsRouteImport } from './routes/api/stats/charts'
import { Route as ApiSireValidateRouteImport } from './routes/api/sire/validate'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSireRegistrosRoute = AppSireRegistrosRouteImport.update({
  id: '/sire-registros',
  path: '/sire-registros',
  getParentRoute: () => AppRoute,
} as any)
const AppPcgeRoute = AppPcgeRouteImport.update({
  id: '/pcge',
  path: '/pcge',
  getParentRoute: () => AppRoute,
} as any)
const AppLibroDiarioRoute = AppLibroDiarioRouteImport.update({
  id: '/libro-diario',
  path: '/libro-diario',
  getParentRoute: () => AppRoute,
} as any)
const AppLibroCajaRoute = AppLibroCajaRouteImport.update({
  id: '/libro-caja',
  path: '/libro-caja',
  getParentRoute: () => AppRoute,
} as any)
const AppFichaRucRoute = AppFichaRucRouteImport.update({
  id: '/ficha-ruc',
  path: '/ficha-ruc',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardEstadisticasRoute =
  AppDashboardEstadisticasRouteImport.update({
    id: '/dashboard-estadisticas',
    path: '/dashboard-estadisticas',
    getParentRoute: () => AppRoute,
  } as any)
const AppContribuyentesRoute = AppContribuyentesRouteImport.update({
  id: '/contribuyentes',
  path: '/contribuyentes',
  getParentRoute: () => AppRoute,
} as any)
const AppCancelacionesRoute = AppCancelacionesRouteImport.update({
  id: '/cancelaciones',
  path: '/cancelaciones',
  getParentRoute: () => AppRoute,
} as any)
const ApiStatsKpisRoute = ApiStatsKpisRouteImport.update({
  id: '/api/stats/kpis',
  path: '/api/stats/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsChartsRoute = ApiStatsChartsRouteImport.update({
  id: '/api/stats/charts',
  path: '/api/stats/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSireValidateRoute = ApiSireValidateRouteImport.update({
  id: '/api/sire/validate',
  path: '/api/sire/validate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cancelaciones': typeof AppCancelacionesRoute
  '/contribuyentes': typeof AppContribuyentesRoute
  '/dashboard-estadisticas': typeof AppDashboardEstadisticasRoute
  '/ficha-ruc': typeof AppFichaRucRoute
  '/libro-caja': typeof AppLibroCajaRoute
  '/libro-diario': typeof AppLibroDiarioRoute
  '/pcge': typeof AppPcgeRoute
  '/sire-registros': typeof AppSireRegistrosRoute
  '/api/sire/validate': typeof ApiSireValidateRoute
  '/api/stats/charts': typeof ApiStatsChartsRoute
  '/api/stats/kpis': typeof ApiStatsKpisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cancelaciones': typeof AppCancelacionesRoute
  '/contribuyentes': typeof AppContribuyentesRoute
  '/dashboard-estadisticas': typeof AppDashboardEstadisticasRoute
  '/ficha-ruc': typeof AppFichaRucRoute
  '/libro-caja': typeof AppLibroCajaRoute
  '/libro-diario': typeof AppLibroDiarioRoute
  '/pcge': typeof AppPcgeRoute
  '/sire-registros': typeof AppSireRegistrosRoute
  '/api/sire/validate': typeof ApiSireValidateRoute
  '/api/stats/charts': typeof ApiStatsChartsRoute
  '/api/stats/kpis': typeof ApiStatsKpisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/cancelaciones': typeof AppCancelacionesRoute
  '/_app/contribuyentes': typeof AppContribuyentesRoute
  '/_app/dashboard-estadisticas': typeof AppDashboardEstadisticasRoute
  '/_app/ficha-ruc': typeof AppFichaRucRoute
  '/_app/libro-caja': typeof AppLibroCajaRoute
  '/_app/libro-diario': typeof AppLibroDiarioRoute
  '/_app/pcge': typeof AppPcgeRoute
  '/_app/sire-registros': typeof AppSireRegistrosRoute
  '/api/sire/validate': typeof ApiSireValidateRoute
  '/api/stats/charts': typeof ApiStatsChartsRoute
  '/api/stats/kpis': typeof ApiStatsKpisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cancelaciones'
    | '/contribuyentes'
    | '/dashboard-estadisticas'
    | '/ficha-ruc'
    | '/libro-caja'
    | '/libro-diario'
    | '/pcge'
    | '/sire-registros'
    | '/api/sire/validate'
    | '/api/stats/charts'
    | '/api/stats/kpis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cancelaciones'
    | '/contribuyentes'
    | '/dashboard-estadisticas'
    | '/ficha-ruc'
    | '/libro-caja'
    | '/libro-diario'
    | '/pcge'
    | '/sire-registros'
    | '/api/sire/validate'
    | '/api/stats/charts'
    | '/api/stats/kpis'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/cancelaciones'
    | '/_app/contribuyentes'
    | '/_app/dashboard-estadisticas'
    | '/_app/ficha-ruc'
    | '/_app/libro-caja'
    | '/_app/libro-diario'
    | '/_app/pcge'
    | '/_app/sire-registros'
    | '/api/sire/validate'
    | '/api/stats/charts'
    | '/api/stats/kpis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSireValidateRoute: typeof ApiSireValidateRoute
  ApiStatsChartsRoute: typeof ApiStatsChartsRoute
  ApiStatsKpisRoute: typeof ApiStatsKpisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sire-registros': {
      id: '/_app/sire-registros'
      path: '/sire-registros'
      fullPath: '/sire-registros'
      preLoaderRoute: typeof AppSireRegistrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcge': {
      id: '/_app/pcge'
      path: '/pcge'
      fullPath: '/pcge'
      preLoaderRoute: typeof AppPcgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/libro-diario': {
      id: '/_app/libro-diario'
      path: '/libro-diario'
      fullPath: '/libro-diario'
      preLoaderRoute: typeof AppLibroDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/libro-caja': {
      id: '/_app/libro-caja'
      path: '/libro-caja'
      fullPath: '/libro-caja'
      preLoaderRoute: typeof AppLibroCajaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ficha-ruc': {
      id: '/_app/ficha-ruc'
      path: '/ficha-ruc'
      fullPath: '/ficha-ruc'
      preLoaderRoute: typeof AppFichaRucRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard-estadisticas': {
      id: '/_app/dashboard-estadisticas'
      path: '/dashboard-estadisticas'
      fullPath: '/dashboard-estadisticas'
      preLoaderRoute: typeof AppDashboardEstadisticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contribuyentes': {
      id: '/_app/contribuyentes'
      path: '/contribuyentes'
      fullPath: '/contribuyentes'
      preLoaderRoute: typeof AppContribuyentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cancelaciones': {
      id: '/_app/cancelaciones'
      path: '/cancelaciones'
      fullPath: '/cancelaciones'
      preLoaderRoute: typeof AppCancelacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/stats/kpis': {
      id: '/api/stats/kpis'
      path: '/api/stats/kpis'
      fullPath: '/api/stats/kpis'
      preLoaderRoute: typeof ApiStatsKpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/charts': {
      id: '/api/stats/charts'
      path: '/api/stats/charts'
      fullPath: '/api/stats/charts'
      preLoaderRoute: typeof ApiStatsChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sire/validate': {
      id: '/api/sire/validate'
      path: '/api/sire/validate'
      fullPath: '/api/sire/validate'
      preLoaderRoute: typeof ApiSireValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCancelacionesRoute: typeof AppCancelacionesRoute
  AppContribuyentesRoute: typeof AppContribuyentesRoute
  AppDashboardEstadisticasRoute: typeof AppDashboardEstadisticasRoute
  AppFichaRucRoute: typeof AppFichaRucRoute
  AppLibroCajaRoute: typeof AppLibroCajaRoute
  AppLibroDiarioRoute: typeof AppLibroDiarioRoute
  AppPcgeRoute: typeof AppPcgeRoute
  AppSireRegistrosRoute: typeof AppSireRegistrosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCancelacionesRoute: AppCancelacionesRoute,
  AppContribuyentesRoute: AppContribuyentesRoute,
  AppDashboardEstadisticasRoute: AppDashboardEstadisticasRoute,
  AppFichaRucRoute: AppFichaRucRoute,
  AppLibroCajaRoute: AppLibroCajaRoute,
  AppLibroDiarioRoute: AppLibroDiarioRoute,
  AppPcgeRoute: AppPcgeRoute,
  AppSireRegistrosRoute: AppSireRegistrosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSireValidateRoute: ApiSireValidateRoute,
  ApiStatsChartsRoute: ApiStatsChartsRoute,
  ApiStatsKpisRoute: ApiStatsKpisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
