// src/integrations/supabase/client.ts - VERSIÓN CORREGIDA
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getPublicEnv } from '@/lib/public-env';

function createSupabaseClient() {
  const SUPABASE_URL =
    getPublicEnv("VITE_SUPABASE_URL") ||
    (import.meta.env.VITE_SUPABASE_URL as string | undefined) ||
    process.env.SUPABASE_URL;
  const SUPABASE_ANON_KEY =
    getPublicEnv("VITE_SUPABASE_ANON_KEY") ||
    (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) ||
    process.env.SUPABASE_ANON_KEY;

  console.log("🔧 [Supabase Client] Inicializando...");
  console.log("  URL:", SUPABASE_URL ? "✅" : "❌ FALTA");
  console.log("  ANON KEY:", SUPABASE_ANON_KEY ? "✅" : "❌ FALTA");

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_ANON_KEY ? ['VITE_SUPABASE_ANON_KEY'] : []),
    ];
    const message = `❌ Missing Supabase environment variable(s): ${missing.join(', ')}`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // 🔥 CONFIGURACIÓN CORRECTA CON PERSISTENCIA
  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      storageKey: 'sb-auth-token',  // ← Clave específica para el token
      persistSession: true,          // ← Guardar sesión
      autoRefreshToken: true,        // ← Renovar automáticamente
      detectSessionInUrl: true,      // ← Detectar sesión en URL
      flowType: 'pkce',              // ← Flujo de autenticación seguro
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Exportar el cliente de Supabase
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      console.log("🚀 [Supabase] Creando instancia del cliente...");
      _supabase = createSupabaseClient();
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});